apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deployment-pod
  template:
    metadata:
      labels:
        app: deployment-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.1
        ports:
        - containerPort: 80

