apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: nginx-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000  # Specify the desired NodePort value here
  type: NodePort

