apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-svc-example
  labels:
    app: deployment-svc-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: SVC-App
  template:
    metadata:
      labels:
        app: SVC-App
    spec:
      containers:
      - name: nginx
        image: ngnix:1.19.1
        ports:
        - containerPort: 80
  

